<a href="https://colab.research.google.com/github/1sazzad/Data-Science-Artificial-Intelligence-Foundation-Course/blob/main/Pandas_%26_DataFrame_Class_11_%26_Class_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

**What is Pandas?**

->Pandas is an open-source Python library used for data manipulation and data analysis.

It provides high-performance data structures and data analysis tools.

The name Pandas comes from:

`PANel DAta System`

Panel data means multidimensional structured data commonly used in statistics and econometrics.

**Simple Definition**

Pandas is a Python library used to store, clean, manipulate, and analyze structured data efficiently.

## **Why Pandas is Used?**  
Data usually comes messy and unorganized format from
* Excel Files
* CSV Files
* Database
* JSON Files
* APIs
* Web Scraping

**Pandas help us to**  
Load data, Clean data, Transform data, Analyze data, Prepare data for machine learning

## **What Problem Pandas Solves**

Imagine you have a dataset like this:

| Name | Age | Salary | City  |
| ---- | --- | ------ | ----- |
| A    | 25  | 40000  | Dhaka |
| B    | 30  | 50000  | Delhi |
| C    | 28  | 45000  | Dhaka |


You may want to:

* Find average salary
* Filter people from Dhaka
* Remove missing values
* Convert data format
* Sort by age
* Group by city

Doing this without Pandas is extremely difficult and slow.

## **Example**

In [1]:
## Without Pandas

data = [
["A",25,40000],
["B",30,50000],
["C",28,45000]
]

total = 0
for row in data:
    total += row[2]

avg = total / len(data)
print(avg)

45000.0

In [2]:
## With Pandas
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 28],
    "Salary": [50000, 60000, 70000, 65000]
}
df = pd.DataFrame(data)
print(df["Salary"].mean())

61250.0

## **Pandas vs NumPy**
| Feature     | NumPy                   | Pandas          |
| ----------- | ----------------------- | --------------- |
| Data Type   | Numerical arrays        | Structured data |
| Data Format | n-dimensional array     | Table format    |
| Use         | Mathematical operations | Data analysis   |
| Labels      | No                      | Yes             |


**Usually:**


```
NumPy → Numerical computation
Pandas → Data manipulation
```

## Advantages of Pandas
✔ Easy data handling  
✔ Fast for large datasets  
✔ Excel-like operations  
✔ Powerful data analysis tools  
✔ Integrates with ML libraries  

## **Important Pandas Functions**

`read_csv()` `head()` `tail()` `info()` `describe()` `loc[]` `iloc[]` `groupby()` `merge()` `concat()` `drop()` `fillna()`

# **1. Pandas Series & DataFrame**

This is the foundation of Pandas.
Almost everything in Pandas is built on these two data structures.

### **Pandas Data Structures**  
There are mainly two data primary data structure
| Data Structure | Dimension | Description               |
| -------------- | --------- | ------------------------- |
| Series         | 1D        | Single column of data     |
| DataFrame      | 2D        | Table of rows and columns |
```
Series  → single column
DataFrame → collection of Series
```
**Example:**
| Name | Age | Salary |
| ---- | --- | ------ |
| A    | 25  | 40000  |
| B    | 30  | 50000  |
```
Name column → Series
Age column → Series
Salary column → Series
```
Together they form a **DataFrame**.

## **Pandas Series**
A **Series** is a **one-dimensional labeled array** capable of holding any data type.
Where each value has an **index label**.  
**Structure**
|Index|Value|
|-----|-----|
|0    |10    |
|1    |20    |
|2    |30    |
|3    |40    |

### **Creating a Series**

In [3]:
# Method 1: From List
import pandas as pd

data = [10,20,30,40]

s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
# Method 2: Custom Index

s = pd.Series([10,20,30], index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [5]:
# Method 3: From Dictionary
data = {
"A":10,
"B":20,
"C":30
}

s = pd.Series(data)

print(s)

A    10
B    20
C    30
dtype: int64

### **Accessing Series Data**

In [6]:
# Access using index
s.iloc[0]

np.int64(10)

In [7]:
# Access multiple values
s.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [8]:
s.values
s.index
s.dtype

dtype('int64')

### **Series Operations**  
Series supports **vectorized operations** (very fast).

In [9]:
s = pd.Series([10,20,30])

print(s + 5)

0    15
1    25
2    35
dtype: int64

### **Important Series Attributes**  
| Attribute | Meaning       |
| --------- | ------------- |
| `.values` | returns data  |
| `.index`  | returns index |
| `.dtype`  | data type     |
| `.shape`  | size          |

In [10]:
print(s.values)
print(s.index)
print(s.dtype)
print(s.shape)

[10 20 30]
RangeIndex(start=0, stop=3, step=1)
int64
(3,)

## **Pandas DataFrame**  
A **DataFrame** is a **two-dimensional labeled data structure** consisting of rows and columns.  
| Name | Age | City   |
| ---- | --- | ------ |
| A    | 25  | Dhaka  |
| B    | 30  | Delhi  |
| C    | 28  | London |

In [11]:
# ==========================================================
# Creating DataFrame
# ==========================================================

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "City": ["Dhaka", "Delhi", "London"]
}

df = pd.DataFrame(data)

print("📊 DataFrame:")
print(df)

📊 DataFrame:
      Name  Age    City
0    Alice   25   Dhaka
1      Bob   30   Delhi
2  Charlie   28  London

### **Important DataFrame Attributes**  
| Attribute  | Meaning        |
| ---------- | -------------- |
| `.shape`   | rows & columns |
| `.columns` | column names   |
| `.index`   | row labels     |
| `.values`  | data values    |

In [12]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.values)

(3, 3)
Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['Alice' 25 'Dhaka']
 ['Bob' 30 'Delhi']
 ['Charlie' 28 'London']]

### **Difference Between Series and DataFrame**  
| Feature   | Series        | DataFrame        |
| --------- | ------------- | ---------------- |
| Dimension | 1D            | 2D               |
| Structure | Single column | Multiple columns |
| Example   | Age column    | Entire table     |

# 2. **DataFrame Indexing & Selection**  
This is one of the most important Pandas skills.
In real data science work, 80% of your time is spent selecting and filtering data.  
**Topics you will learn**  
* column selection
* row selection
* loc
* iloc
* conditional filtering

**Why Indexing & Selection is Important**  
Real dataset are large
| Name | Age | Salary | City   |
| ---- | --- | ------ | ------ |
| A    | 25  | 40000  | Dhaka  |
| B    | 30  | 50000  | Delhi  |
| C    | 28  | 45000  | Dhaka  |
| D    | 35  | 60000  | London |

You may want to:  
* select a single column  
* select multiple columns  
* select specific rows  
* filter rows based on conditions  
* extract subsets of data

All these operations use indexing and selection.

In [13]:
# Create a dataset
import pandas as pd

data = {
"Name":["Alice","Bob","Charlie","David"],
"Age":[25,30,28,35],
"Salary":[40000,50000,45000,60000],
"City":["Dhaka","Delhi","Dhaka","London"]
}

df = pd.DataFrame(data)

df

      Name  Age  Salary    City
0    Alice   25   40000   Dhaka
1      Bob   30   50000   Delhi
2  Charlie   28   45000   Dhaka
3    David   35   60000  London

##  **Selecting Column**

In [14]:
# Select Single Column
print("="*50)
print('Printing Single column')
print(df['Age'])
# Select Multiple Column
print("="*50)
print('Printing Multiple column')
print(df[['Age','Salary']])

==================================================
Printing Single column
0    25
1    30
2    28
3    35
Name: Age, dtype: int64
==================================================
Printing Multiple column
   Age  Salary
0   25   40000
1   30   50000
2   28   45000
3   35   60000

## **Selecting Rows**  
There are two main methods.
| Method | Meaning                 |
| ------ | ----------------------- |
| `loc`    | label-based indexing    |
| `iloc`   | position-based indexing |

### **`.loc[]` — Label Based Selection**   
```
df.loc[row_label , column_label]
```

In [15]:
# ==========================================================
# Selecting Rows using .loc
# ==========================================================

# Select single row
print("🔹 Select Single Row")
print("=" * 40)
print(df.loc[0])


# Select row and column
print("\n🔹 Select Row and Column")
print("=" * 40)
print(df.loc[0, "Age"])


# Select multiple rows
print("\n🔹 Select Multiple Rows")
print("=" * 40)
print(df.loc[0:2])

🔹 Select Single Row
========================================
Name      Alice
Age          25
Salary    40000
City      Dhaka
Name: 0, dtype: object

🔹 Select Row and Column
========================================
25

🔹 Select Multiple Rows
========================================
      Name  Age  Salary   City
0    Alice   25   40000  Dhaka
1      Bob   30   50000  Delhi
2  Charlie   28   45000  Dhaka

### **`.iloc[]` — Position Based Selection**  
```
df.iloc[row_position , column_position]
```

In [16]:
# ==========================================================
# Selecting Rows using .iloc
# ==========================================================

# Select single row
print("🔹 Select Single Row")
print("=" * 40)
print(df.iloc[0])


# Select specific cell
print("\n🔹 Select Specific Cell")
print("=" * 40)
print(df.iloc[0, 1])


# Select multiple rows
print("\n🔹 Select Multiple Rows")
print("=" * 40)
print(df.iloc[0:3])

🔹 Select Single Row
========================================
Name      Alice
Age          25
Salary    40000
City      Dhaka
Name: 0, dtype: object

🔹 Select Specific Cell
========================================
25

🔹 Select Multiple Rows
========================================
      Name  Age  Salary   City
0    Alice   25   40000  Dhaka
1      Bob   30   50000  Delhi
2  Charlie   28   45000  Dhaka

### **Difference Between `.loc` and `.iloc`**  
| Feature           | loc           | iloc             |
| ----------------- | ------------- | ---------------- |
| Index type        | label         | position         |
| Uses column names | yes           | no               |
| Uses numbers      | label numbers | position numbers |

## **Conditional Selection (Very Important)**
**Symbols**  
| Symbol | Meaning |
| ------ | ------- |
| &      | AND     |
| |      | OR      |
| ~      | NOT     |

In [17]:
# ==========================================================
# Conditional Selection (Filtering Data)
# ==========================================================

# Select people with age > 28
print("🔹 People with Age > 28")
print("=" * 40)
print(df[df["Age"] > 28])


# Multiple conditions
print("\n🔹 People with Age > 25 and City = Dhaka")
print("=" * 40)
print(df[(df["Age"] > 25) & (df["City"] == "Dhaka")])


# ==========================================================
# Selecting Specific Columns After Filtering
# ==========================================================

# People with age > 28 but show only Name
print("\n🔹 People with Age > 28 (Only Name)")
print("=" * 40)
print(df[df["Age"] > 28]["Name"])


# Selecting rows and columns together
print("\n🔹 People with Age > 28 (Name and Age)")
print("=" * 40)
print(df.loc[df["Age"] > 28, ["Name", "Age"]])

🔹 People with Age > 28
========================================
    Name  Age  Salary    City
1    Bob   30   50000   Delhi
3  David   35   60000  London

🔹 People with Age > 25 and City = Dhaka
========================================
      Name  Age  Salary   City
2  Charlie   28   45000  Dhaka

🔹 People with Age > 28 (Only Name)
========================================
1      Bob
3    David
Name: Name, dtype: object

🔹 People with Age > 28 (Name and Age)
========================================
    Name  Age
1    Bob   30
3  David   35

# **Data Inspection & Exploration**
Whenever a data scientist receives a dataset, **the first task is to understand the data**.

We do data inspection to answer questions like:  
* How many rows and columns exist?
* What are the data types?
* Are there missing values?
* What are the statistics of the data?

**You will learn**  
`head()` `tail()` `shape` `columns` `info()` `describe()` `value_counts()` `unique()` `nunique()` `sample()`

In [18]:
# ==========
# Create a dataset first

import pandas as pd

data = {
    "Name": [
        "Alice","Bob","Charlie","David","Eva",
        "Frank","Grace","Henry","Ivy","Jack",
        "Karen","Leo","Mona","Nina","Oscar",
        "Paul","Quinn","Rose","Sam","Tina",
        "Uma","Victor","Wendy","Xavier","Yara",
        "Zack","Adam","Bella","Chris","Diana",
        "Ethan","Fiona","George","Hanna","Ian",
        "Julia","Kevin","Lara","Mike","Nora",
        "Owen","Pia","Ryan","Sara","Tom",
        "Usha","Vik","Will","Xena","Yusuf"
    ],

    "Age": [
        25,30,28,35,40,
        22,27,31,29,33,
        26,34,24,32,36,
        28,30,27,35,31,
        29,38,26,33,24,
        37,28,23,34,30,
        27,35,29,31,26,
        32,28,36,30,25,
        34,27,33,29,31,
        28,35,26,32,30
    ],

    "Salary": [
        40000,50000,45000,60000,65000,
        38000,42000,52000,47000,55000,
        43000,58000,39000,51000,62000,
        46000,50000,44000,60000,53000,
        48000,67000,42000,54000,41000,
        63000,45000,37000,56000,52000,
        44000,61000,47000,52000,43000,
        50000,46000,62000,51000,40000,
        59000,43000,54000,48000,52000,
        46000,60000,42000,55000,50000
    ],

    "City": [
        "Dhaka","Delhi","Dhaka","London","Delhi",
        "London","Dhaka","Delhi","Dhaka","London",
        "Delhi","Dhaka","London","Delhi","Dhaka",
        "London","Delhi","Dhaka","London","Delhi",
        "Dhaka","London","Delhi","Dhaka","London",
        "Delhi","Dhaka","London","Delhi","Dhaka",
        "London","Delhi","Dhaka","London","Delhi",
        "Dhaka","London","Delhi","Dhaka","London",
        "Delhi","Dhaka","London","Delhi","Dhaka",
        "London","Delhi","Dhaka","London","Delhi"
    ]
}

df = pd.DataFrame(data)

df.head()

      Name  Age  Salary    City
0    Alice   25   40000   Dhaka
1      Bob   30   50000   Delhi
2  Charlie   28   45000   Dhaka
3    David   35   60000  London
4      Eva   40   65000   Delhi

In [19]:
# head() — View First Rows
# Shows first 5 rows
df.head()

      Name  Age  Salary    City
0    Alice   25   40000   Dhaka
1      Bob   30   50000   Delhi
2  Charlie   28   45000   Dhaka
3    David   35   60000  London
4      Eva   40   65000   Delhi

In [20]:
# To show specific number of rows from first use index
df.head(10)

      Name  Age  Salary    City
0    Alice   25   40000   Dhaka
1      Bob   30   50000   Delhi
2  Charlie   28   45000   Dhaka
3    David   35   60000  London
4      Eva   40   65000   Delhi
5    Frank   22   38000  London
6    Grace   27   42000   Dhaka
7    Henry   31   52000   Delhi
8      Ivy   29   47000   Dhaka
9     Jack   33   55000  London

In [21]:
# tail() — View First Rows
# Shows last 5 rows
df.tail()

     Name  Age  Salary    City
45   Usha   28   46000  London
46    Vik   35   60000   Delhi
47   Will   26   42000   Dhaka
48   Xena   32   55000  London
49  Yusuf   30   50000   Delhi

In [22]:
# shape — Dataset Size
# This tells us the dimention of the dataset.
df.shape

(50, 4)

In [23]:
# columns — Column Names
# Shows the column names
df.columns

Index(['Name', 'Age', 'Salary', 'City'], dtype='object')

In [24]:
# info() — Dataset Summary
# Tells us the information about DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     object
 1   Age     50 non-null     int64
 2   Salary  50 non-null     int64
 3   City    50 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.7+ KB

**It tells us:**  
| Information | Meaning            |
| ----------- | ------------------ |
| entries     | number of rows     |
| columns     | number of features |
| dtype       | data type          |
| non-null    | missing values     |
**Data types:**
| Information | Meaning            |
| ----------- | ------------------ |
| entries     | number of rows     |
| columns     | number of features |
| dtype       | data type          |
| non-null    | missing values     |

In [25]:
# describe() — Statistical Summary
# Important for numerical analysis
df.describe().round(2)

         Age    Salary
count  50.00     50.00
mean   30.18  50200.00
std     4.12   7732.78
min    22.00  37000.00
25%    27.00  44000.00
50%    30.00  50000.00
75%    33.00  55000.00
max    40.00  67000.00

In [26]:
# value_counts() — Frequency Count
# Useful for categorical variables
df['City'].value_counts()

City
Dhaka     17
Delhi     17
London    16
Name: count, dtype: int64

In [27]:
# unique() — Unique Values
# Useful to see distinct categories
df['Age'].unique()

array([25, 30, 28, 35, 40, 22, 27, 31, 29, 33, 26, 34, 24, 32, 36, 38, 37,
       23])

In [28]:
# nunique() — Number of Unique Values
df['Age'].nunique()

18

In [29]:
# sample() — Random Rows
df.sample(2)

      Name  Age  Salary    City
23  Xavier   33   54000   Dhaka
21  Victor   38   67000  London

# **Data Cleaning in Pandas**  
In real-world datasets, data is almost never clean.  
**Common problems:**  
* Missing values
* Duplicate records
* Incorrect data types
* Inconsistent values
* Outliers  

Data cleaning is also called **Data Preprocessing**.  
**You will learn**  
`isnull()` `dropna()` `fillna()` `duplicated()` `drop_duplicates()` `astype()` `replace()` `rename()` `drop()`

In [30]:
# Let's create a dataset that contains missing values.
import pandas as pd
import numpy as np

data = {
"Name":[
"Alice","Alice","Bob","Charlie","David","Eva",
"Frank","Grace","Henry","Ivy","Jack",
"Karen","Leo","Mona","Nina","Oscar",
"Paul","Quinn","Rose","Sam","Tina",
"Uma","Victor","Wendy","Xavier","Yara",
"Zack","Adam","Bella","Chris","Diana",
"Ethan","Fiona","George","Hanna","Ian",
"Julia","Kevin","Lara","Mike","Nora",
"Owen","Pia","Ryan","Sara","Tom",
"Usha","Vik","Will","Xena","Yusuf"
],

"Age":[
25,25,30,np.nan,35,40,
22,np.nan,31,29,33,
26,34,24,32,36,
28,30,np.nan,35,31,
29,38,26,33,np.nan,
37,28,23,34,30,
27,35,29,np.nan,26,
32,28,36,30,25,
34,27,33,29,31,
28,35,26,np.nan,30
],

"Salary":[
40000,40000,50000,45000,np.nan,65000,
38000,42000,np.nan,47000,55000,
43000,58000,39000,51000,np.nan,
46000,50000,44000,60000,53000,
48000,67000,42000,54000,41000,
63000,np.nan,37000,56000,52000,
44000,61000,47000,52000,43000,
50000,np.nan,62000,51000,40000,
59000,43000,54000,np.nan,52000,
46000,60000,42000,55000,50000
],

"City":[
"Dhaka","Dhaka","Delhi","dhaka","London",None,
"London","Dhaka","Delhi"," Dhaka ","London",
"Delhi","dhaka","London","Delhi","Dhaka",
"London","Delhi","Dhaka","London","Delhi",
"Dhaka","London","Delhi","Dhaka","London",
"Delhi","Dhaka","London","Delhi","Dhaka",
"London","Delhi","Dhaka","London","Delhi",
"Dhaka","London","Delhi","Dhaka","London",
"Delhi","Dhaka","London","Delhi","Dhaka",
"London","Delhi","Dhaka","London",None
]
}

df = pd.DataFrame(data)

df.head()

      Name   Age   Salary    City
0    Alice  25.0  40000.0   Dhaka
1    Alice  25.0  40000.0   Dhaka
2      Bob  30.0  50000.0   Delhi
3  Charlie   NaN  45000.0   dhaka
4    David  35.0      NaN  London

## **Pandas Data Cleaning Functions Summary**  
| Function | Syntax | Function Details | Example |
|---|---|---|---|
| `isnull()` | `df.isnull()` | Detects missing values in the dataset.<br>Returns **True** where data is missing. | `df.isnull()` |
| `isnull().sum()` | `df.isnull().sum()` | Counts missing values in each column.<br>Very common in ML preprocessing. | `df.isnull().sum()` |
| `dropna()` | `df.dropna()` | Removes rows containing missing values.<br>Rows with `NaN` are deleted. | `df.dropna()` |
| `dropna(axis=1)` | `df.dropna(axis=1)` | Removes columns containing missing values.<br>`axis=1` means column operation. | `df.dropna(axis=1)` |
| `fillna()` | `df.fillna(value)` | Replaces missing values with a specified value.<br>Useful when you don't want to remove rows. | `df.fillna(0)` |
| `fillna(mean)` | `df["Age"].fillna(df["Age"].mean())` | Replaces missing numeric values with the **mean**.<br>Helps preserve overall data distribution. | `df["Age"].fillna(df["Age"].mean())` |
| `fillna(median)` | `df["Age"].fillna(df["Age"].median())` | Replaces missing values with the **median**.<br>Better when outliers exist. | `df["Age"].fillna(df["Age"].median())` |
| `fillna(mode)` | `df["City"].fillna(df["City"].mode()[0])` | Replaces missing categorical values.<br>Uses the **most frequent value**. | `df["City"].fillna(df["City"].mode()[0])` |
| `duplicated()` | `df.duplicated()` | Detects duplicate rows.<br>Returns **True** for duplicates. | `df.duplicated()` |
| `duplicated().sum()` | `df.duplicated().sum()` | Counts the number of duplicate rows.<br>Useful for dataset inspection. | `df.duplicated().sum()` |
| `drop_duplicates()` | `df.drop_duplicates()` | Removes duplicate rows from the dataset.<br>Keeps only unique records. | `df.drop_duplicates()` |
| `astype()` | `df["Age"].astype(int)` | Converts data type of a column.<br>Used when data types are incorrect. | `df["Age"] = df["Age"].astype(int)` |
| `replace()` | `df["City"].replace(old,new)` | Replaces incorrect or inconsistent values.<br>Useful for cleaning categorical data. | `df["City"].replace("Dacca","Dhaka")` |
| `rename()` | `df.rename(columns={})` | Renames column names.<br>Helps make dataset easier to understand. | `df.rename(columns={"Customer Name":"Name"})` |
| `drop()` | `df.drop(column, axis=1)` | Removes columns or rows from the dataset.<br>`axis=1` removes columns. | `df.drop("Salary", axis=1)` |

In [31]:
df["City"].mode()[0]

'London'

# **Data Manipulation in Pandas**  
**You will learn:**  
`sort_values()` `groupby()` `agg()` `apply()` `map()` `lambda` `feature engineering`

In [32]:
# Example Dataset
import pandas as pd

data = {
"Product":["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop"],
"Price":[800,500,300,850,520,310,790],
"Quantity":[2,5,3,1,4,2,3],
"City":["Dhaka","Delhi","Dhaka","London","Delhi","Dhaka","London"]
}

df = pd.DataFrame(data)

df

  Product  Price  Quantity    City
0  Laptop    800         2   Dhaka
1   Phone    500         5   Delhi
2  Tablet    300         3   Dhaka
3  Laptop    850         1  London
4   Phone    520         4   Delhi
5  Tablet    310         2   Dhaka
6  Laptop    790         3  London

## **Pandas Data Manipulation Functions Summary**  
| Function | Syntax | Function Details | Example |
|---|---|---|---|
| `sort_values()` | `df.sort_values(column)` | Sorts the dataset based on column values.<br>Default order is ascending. | `df.sort_values("Price")` |
| `sort_values(desc)` | `df.sort_values(column, ascending=False)` | Sorts data in descending order.<br>Largest values appear first. | `df.sort_values("Price", ascending=False)` |
| `sort_values(multiple)` | `df.sort_values([col1,col2])` | Sorts dataset by multiple columns.<br>Sorting happens sequentially from left to right. | `df.sort_values(["City","Price"])` |
| Feature Engineering | `df["NewCol"] = expression` | Creates new columns from existing data.<br>Very important in machine learning projects. | `df["Revenue"] = df["Price"] * df["Quantity"]` |
| `groupby()` | `df.groupby(column)` | Groups dataset by a column.<br>Used for aggregation and analysis. | `df.groupby("City")` |
| `groupby().mean()` | `df.groupby(col).mean()` | Calculates average values within groups.<br>Useful for analyzing grouped statistics. | `df.groupby("Product").mean(numeric_only=True)` |
| `groupby().sum()` | `df.groupby(col).sum()` | Calculates total values within groups.<br>Often used for sales or revenue analysis. | `df.groupby("City").sum(numeric_only=True)` |
| `agg()` | `df.groupby(col).agg(func)` | Performs multiple aggregation operations.<br>Allows several statistics at once. | `df.groupby("Product").agg(["mean","max","min"])` |
| `apply()` | `df[column].apply(function)` | Applies a custom function to each value.<br>Useful for advanced transformations. | `df["Price"].apply(lambda x: x * 1.10)` |
| `map()` | `df[column].map(dictionary)` | Maps values to new categories.<br>Often used for categorical transformations. | `df["Category"] = df["Product"].map(product_map)` |
| `lambda` | `lambda args : expression` | Creates a small anonymous function.<br>Commonly used with `apply()` for quick transformations. | `lambda x: x * 2` |

# **Combining Data in Pandas**  
In real data science projects, data rarely comes in one single table.  
Usually you have multiple datasets like:  
**Customers Table**  
| CustomerID | Name  |
| ---------- | ----- |
| 1          | Alice |
| 2          | Bob   |  

**Orders Table**  
| CustomerID | Product |
| ---------- | ------- |
| 1          | Laptop  |
| 2          | Phone   |

**You will learn:**  
`concat()` `merge()` `join()` `inner join` `left join` `right join` `outer join`

In [33]:
# Create dataset
import pandas as pd

df1 = pd.DataFrame({
"Name":["Alice","Bob"],
"Age":[25,30]
})

df2 = pd.DataFrame({
"Name":["Charlie","David"],
"Age":[28,35]
})

In [34]:
# df1
df1

    Name  Age
0  Alice   25
1    Bob   30

In [35]:
# df2
df2

      Name  Age
0  Charlie   28
1    David   35

## **Pandas Dataset Combination Functions**  
| Function | Syntax | Function Details | Example |
|---|---|---|---|
| `concat()` | `pd.concat([df1, df2])` | Combines multiple DataFrames.<br>Stacks datasets together.<br>Default operation is row-wise. | `pd.concat([df1, df2])` |
| `concat(axis=1)` | `pd.concat([df1, df2], axis=1)` | Combines DataFrames column-wise.<br>Instead of stacking rows, columns are merged side-by-side. | `pd.concat([df1, df2], axis=1)` |
| `merge()` | `pd.merge(df1, df2, on="column")` | Combines datasets similar to SQL JOIN.<br>Uses a common column as a key.<br>Most commonly used method in data science. | `pd.merge(customers, orders, on="CustomerID")` |
| `merge(inner)` | `pd.merge(df1, df2, on="col", how="inner")` | Returns only matching rows.<br>Records must exist in both datasets. | `pd.merge(customers, orders, on="CustomerID", how="inner")` |
| `merge(left)` | `pd.merge(df1, df2, on="col", how="left")` | Keeps all rows from the left table.<br>Adds matching rows from the right table.<br>Missing matches become `NaN`. | `pd.merge(customers, orders, on="CustomerID", how="left")` |
| `merge(right)` | `pd.merge(df1, df2, on="col", how="right")` | Keeps all rows from the right table.<br>Adds matching rows from the left table. | `pd.merge(customers, orders, on="CustomerID", how="right")` |
| `merge(outer)` | `pd.merge(df1, df2, on="col", how="outer")` | Returns all rows from both tables.<br>Unmatched values are filled with `NaN`. | `pd.merge(customers, orders, on="CustomerID", how="outer")` |
| `join()` | `df1.join(df2)` | Combines DataFrames using index.<br>Less flexible than `merge()`.<br>Often used when indexes already match. | `df1.join(df2)` |

# **Advanced Pandas Operations**  
**We will study these powerful tools:**  
`pivot_table()` `crosstab()` `multi-index` `stack()` `unstack()`

In [36]:
# Dataset
import pandas as pd

data = {
"City":["Dhaka","Dhaka","Delhi","Delhi","London","London"],
"Product":["Laptop","Phone","Laptop","Tablet","Phone","Tablet"],
"Sales":[2000,1500,1800,1200,1600,900]
}

df = pd.DataFrame(data)

df

     City Product  Sales
0   Dhaka  Laptop   2000
1   Dhaka   Phone   1500
2   Delhi  Laptop   1800
3   Delhi  Tablet   1200
4  London   Phone   1600
5  London  Tablet    900

## **Heading**  

| Function | Syntax | Function Details | Example |
|---|---|---|---|
| `pivot_table()` | `pd.pivot_table(df, values, index)` | Creates a summary table from a dataset.<br>Similar to Excel Pivot Tables.<br>Default aggregation is **mean**. | `pd.pivot_table(df, values="Sales", index="City")` |
| `pivot_table(sum)` | `pd.pivot_table(df, values, index, aggfunc="sum")` | Changes aggregation function.<br>Useful for totals instead of averages. | `pd.pivot_table(df, values="Sales", index="City", aggfunc="sum")` |
| `pivot_table(2D)` | `pd.pivot_table(df, values, index, columns)` | Creates a 2-dimensional pivot table.<br>Rows and columns represent categories. | `pd.pivot_table(df, values="Sales", index="City", columns="Product", aggfunc="sum")` |
| `crosstab()` | `pd.crosstab(col1, col2)` | Creates a contingency table.<br>Counts frequency of combinations between variables. | `pd.crosstab(df["City"], df["Product"])` |
| `multi-index` | `df.set_index([col1,col2])` | Creates hierarchical indexing.<br>Multiple levels of index for structured data. | `df.set_index(["City","Product"])` |
| `stack()` | `df.stack()` | Converts columns into rows.<br>Used for reshaping pivot tables. | `pivot.stack()` |
| `unstack()` | `df.unstack()` | Opposite of stack().<br>Converts row index levels into columns. | `pivot.stack().unstack()` |

# **Time Series Handling in Pandas**  
Time series data means **data indexed by time**.  
**You will learn:**  
`to_datetime()` `date_range()` `resample()` `rolling()` `shift()` `datetime_features`

In [37]:
import pandas as pd

data = {
"Date":["2024-01-01","2024-01-02","2024-01-03"],
"Sales":[100,120,90]
}

df = pd.DataFrame(data)

## **Heading**  

| Function | Syntax | Function Details | Example |
|---|---|---|---|
| `to_datetime()` | `pd.to_datetime(column)` | Converts date strings into datetime format.<br>Enables powerful time-based operations in Pandas. | `df["Date"] = pd.to_datetime(df["Date"])` |
| `set_index()` | `df.set_index("Date")` | Sets date column as index.<br>Required for most time-series analysis operations. | `df.set_index("Date", inplace=True)` |
| `date_range()` | `pd.date_range(start, periods)` | Generates sequences of dates automatically.<br>Useful for creating time series datasets. | `pd.date_range(start="2024-01-01", periods=5)` |
| `datetime features` | `df.index.year` `df.index.month` | Extracts date components such as year, month, day.<br>Used for feature engineering in ML. | `df.index.month` |
| `resample()` | `df.resample("M")` | Changes time frequency of data.<br>Often used for aggregating daily data to weekly or monthly. | `df.resample("M").sum()` |
| `resample codes` | `"D" "W" "M" "Y"` | Defines resampling frequency.<br>D = daily, W = weekly, M = monthly, Y = yearly. | `df.resample("W").sum()` |
| `rolling()` | `df[column].rolling(window=n)` | Performs moving window calculations.<br>Used for smoothing or trend analysis. | `df["Sales"].rolling(window=3).mean()` |
| `shift()` | `df[column].shift(n)` | Shifts data forward or backward.<br>Common in time-series feature engineering. | `df["Sales"].shift(1)` |